###

POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "testUser",
  "password": "123456"
}

###

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "testUser",
    "password": "1234567"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYmlvIiwiaWF0IjoxNjIzMjMzMTc5fQ.3ejKU0EWMCNiHx1wBZSJZuITqI3lwb7yplbhucnsvuM
